# Site settings
title: Dragonly
email: liyilongko@163.com
description: >
  Personal blog of Dragonly<liyilongko@163.com>.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dragonly.github.io/"
# twitter_username: jekyllrb
github_username:  dragonly

# Build settings
sass:
  style: :compressed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
